CnCNet/xna-cncnet-client

- DTAConfig/DTAConfig.csproj
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Domain/Multiplayer/PlayerHouseInfo.cs
- DXMainClient/Online/FileHashCalculator.cs
Below are changes specifically for YR I'd like to include to keep maintaining with master simple.
> YR specific changes

- ClientCore/Settings/UserINISettings.cs
- DTAConfig/DisplayOptionsPanel.cs
- DXMainClient/Online/FileHashCalculator.cs
Win8 TSDDRAW for YR. Ask @FunkyFr3sh for details of what this is regarding.
> Add Win8 TSDDRAW compatibility INI settings for spawner

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/Domain/Multiplayer/CnCNet/CnCNetPlayerCountTask.cs
Could also possibly look at: 
- Changing the online count when the channel is changed.
- Making the Text customizable in an INI file somewhere.
> Add online count to Lobby

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Online/CnCNetGameCheck.cs
Kills game instance if Cheat Engine is in use.
> Add first pass at checks for cheat engine usage

- BuildScripts/FindMSBuild.bat
BuildTools = tools needed to compile sans VS2017 itself:
https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15
> Implement BuildTools MSBuild finding

- DTAConfig/OptionPanels/UpdaterOptionsPanel.cs
...which is effectively a shortcut to delete `version` file so that the updater verifies the files and asks for an update. It is located under updater options tab and is inactive if there's already no `version` file or the user confirmed that he wants to delete it (the deletion happens only if the user presses `Save` and not `Cancel`).
> Implement Force Update button

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
Only available at CnCNet lobby. Does the same as the chat command.
> Add "Change Tunnel" button to CnCNet game lobby

- DXMainClient/DXGUI/Generic/MainMenu.cs
- DXMainClient/DXGUI/Generic/TopBar.cs
As reported by @Rampstring. ![Screenshot of an issue](https://cdn.discordapp.com/attachments/680366050642100238/684154183770963987/unknown.png)
> LAN mode topbar bugfix

- ClientCore/Settings/UserINISettings.cs
- DTAConfig/OptionPanels/CnCNetOptionsPanel.cs
- DXMainClient/DXGUI/Generic/LoadingScreen.cs
- DXMainClient/DXGUI/Generic/MainMenu.cs
- LICENSE.md
Added new license texts and added code to show privacy notice if it hasn't been shown already.
> Legal stuff improvements

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
- DXMainClient/Online/CnCNetUserData.cs
Users can now block other users using PM window list. Since you can't block a user who is offline due to how IRC works the option is grayed out on offline users from friend list.
> Implement blocking users from PM window

- DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
Adds back the invite option in friends list player context menu.
> Fix invite option not showing up in friends list context menu

- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
> Fix map location context menu becoming unresponsive on every player option change

- DXMainClient/Domain/SavedGame.cs
This PR fixed the bug that the name of saved games can't be displayed correctly, when the name contains non-ASCII characters. Now the program is able to handle MOST of the UTF-16 LE string correctly.
Also, see the [screenshot](https://ibb.co/3BdFr64).
> Bug fix: Parse the UTF-16 LE string in saved game files

- DXMainClient/Online/Connection.cs
Hi there! I have rewriteen the function used to filter the Lobby server.
- Combine the lists of ports bound to the same IP address ( #208 , 47b44f08e0506e02774ce64661928cf40c01e3f5 from #209 ).
- Do not exclude servers that did not respond to ICMP messages ( #141 , 4b7172e745f0df5420f33c4cd39df29c1f4d05a9 from #142 ).
- Better exception handling.
- No thread safety issue.
- Better code structure.
- Change the return value type from IEnumerable\<T\> to IList\<T\>.
Please see the commit message for details.
> ### Commit message
> 3. If the latency is greater than 400 ms, ignore the server.
> 
> from: https://github.com/CnCNet/xna-cncnet-client/pull/142#issue-405172369
My apologies. This is really a stupid idea. Players who were able to log in slowly may now be unable to log in at all. It is …
> Rewrite the Lobby server filter.

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyCheckBox.cs
> Fix DisallowedSideIndex bug

- DXMainClient/DXMainClient.csproj
- DXMainClient/Domain/Multiplayer/CustomMapCache.cs
- DXMainClient/Domain/Multiplayer/MapLoader.cs
move custom_map_cache
version custom_map_cache
fix issue with null SHAs when loading from cache
> fix issue with null SHAs when loading from cache

- ClientCore/Settings/UserINISettings.cs
- DTAConfig/OptionPanels/CnCNetOptionsPanel.cs
- DTAConfig/OptionsWindow.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
> Disable all private messages

- ClientCore/ClientCore.csproj
- ClientCore/Enums/AllowPrivateMessagesFromEnum.cs
- ClientCore/Settings/UserINISettings.cs
- DTAConfig/OptionPanels/CnCNetOptionsPanel.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
> Convert private message checkboxes to drop down

- DXMainClient/DXGUI/Multiplayer/GameListBox.cs
- DXMainClient/Domain/Multiplayer/CnCNet/HostedCnCNetGame.cs
- DXMainClient/Domain/Multiplayer/GenericHostedGame.cs
https://github.com/CnCNet/cncnet-yr-client-package/issues/74
> Fix casting error for lan games

- ClientCore/ClientCore.csproj
- ClientCore/Settings/StringListSetting.cs
- ClientCore/Settings/UserINISettings.cs
- ClientGUI/ToolTip.cs
- ClientGUI/XNAClientButton.cs
- DXMainClient/DXGUI/Generic/LoadingScreen.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameModeMapFilter.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
- DXMainClient/DXGUI/Multiplayer/LANLobby.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Domain/Multiplayer/GameMode.cs
- DXMainClient/Domain/Multiplayer/GameModeMap.cs
- DXMainClient/Domain/Multiplayer/GameModeMapCollection.cs
- DXMainClient/Domain/Multiplayer/Map.cs
- DXMainClient/Domain/Multiplayer/MapLoader.cs
- DXMainClient/Online/EventArguments/FavoriteMapEventArgs.cs
First, this PR is against the branch "team-start-mapping", because I based it off of that branch, due to the significant changes in it. That way, this PR will appear cleaner and won't include the changes from that branch in this PR, had it been against the develop branch. When "team-start-mapping" gets merged into develop, I will change the target branch of this PR to be develop as well.
A couple of things done here:
- First of all, when a favorite is created, the user isn't just marking the map as a favorite. They're marking the map for a given game mode as a favorite. So, I created a **GameModeMap** class that is the instance of a **Map** for a specific **GameMode**. This also has a property of **IsFavorite** to mark that specific instance as a favorite. This collection is instantiated …
> Favorite Maps

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
I know we talked about putting continued dev on hold until we get the translation and TS PRs merged, but I think enough people have been chiming in about this that it might warranted to get this included real quick.
> Show General Chat (#cncnet) banned message only in General Chat lobby

- DXMainClient/DXGUI/Multiplayer/CnCNet/RecentPlayerTable.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
Some literal texts in the source code were replaced after some PRs. This PR adds the missings.
> Fix missing translation labels

- DTAConfig/Settings/FileSourceDestinationInfo.cs
This PR fixes #381 as suggested by @frg2089.
> Fix crash on saving options

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
This is based on PR https://github.com/CnCNet/xna-cncnet-client/pull/420
The second commit here is the only change. @CCHyper
> #419 Write the original scenario filename to the spawnmap.ini [Basic] section.

- ClientCore/LoadingScreenController.cs
> Custom loading screen path is incorrect #439

- DXMainClient/Domain/Multiplayer/MapLoader.cs
> 434-full-map-path-preview-show-in-chat

- ClientCore/CnCNet5/GameCollection.cs
> Fix typo in registries

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
> Fix an inconsistent translation label

- DXMainClient/DXGUI/Multiplayer/GameListBox.cs
- DXMainClient/Domain/Multiplayer/LAN/HostedLANGame.cs
> Fix crash on unknown LAN games

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
Unhardcode string from [1810e44](https://github.com/CnCNet/xna-cncnet-client/commit/1810e44e8fd6e43e34e454710c1a9c9239b01b8b#diff-8288b2a427397578c24040412ece4160f93e250af073d4f376042d8b00c525ce) commit in exception message.
> Unhardcode string from 1810e44 commit

- ClientGUI/XNAClientToggleButton.cs
- Docs/INISystem.md
Make XNAClientToggleButton supported ParseControlIniAttribute
> Make XNAClientToggleButton supported ParseControlIniAttribute

- ClientUpdater/CustomComponent.cs
- ClientUpdater/Updater.cs
- DTAConfig/OptionPanels/ComponentsPanel.cs
- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
> Disable readonly property before deleting files

- DXMainClient/DXGUI/Multiplayer/GameInformationPanel.cs
Resolves https://github.com/CnCNet/xna-cncnet-client/issues/617
> Fix height of game info panel

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
As reported by doofus and Neogrant on Discord.
> Fix null map on handleoptionsrequest

- DXMainClient/Online/Connection.cs
Fix for 
https://github.com/CnCNet/cncnet-yr-client-package/issues/443
Possibly fixes this one too but I haven't tested.
https://github.com/CnCNet/xna-cncnet-client/issues/640
> Fix client not reaching disconnect code with unintentional disconnects.

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/Online/Channel.cs
- DXMainClient/Online/UnsortedUserCollection.cs
No behaviors are changed in this PR. Just minor revision to hint developers about the possible pitfalls
> Mark some pitfalls on UserCollection

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
Currently if you have "Favorite maps" selected and click "Pick random map", no map will be selected. This PR fixes that.
> Fix PickRandomMap not working with Favourited map list

- ClientCore/ClientConfiguration.cs
- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
> Potential fix for delayed game loading

- ClientGUI/GameProcessLogic.cs
> Fix L10N for message boxes in `GameProcessLogic` class

- Directory.Packages.props
Update Rampastring.XNAUI from 2.5.1 to 2.7.1
> Update Rampastring.XNAUI to add support for text selection in textboxes

- DXMainClient/DXGUI/Multiplayer/GameListBox.cs
Required for latest Rapastring.XNAUI
> Use correct property for clearing items

- DTAConfig/OptionPanels/AudioOptionsPanel.cs
- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
- DTAConfig/OptionPanels/GameOptionsPanel.cs
Fix #674 and other issues in future naming refactoring for option panels.
> Fix objects naming in `OptionsPanel`

- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
Bug was [introduced](https://github.com/CnCNet/xna-cncnet-client/pull/688/files#diff-466471f2cc3172ff70962f63dd2a5d907afe69404b1979754912ddc74f751553) by #688.
> Fix bug when non TS client tries to save options

- ClientCore/I18N/Translation.cs
> Fix a bug where the locale name was not localized to the native language.

- DXMainClient/Domain/Multiplayer/MapLoader.cs
Blame me on https://github.com/CnCNet/xna-cncnet-client/commit/593adf0b1223f2c6801f3441ab7d1655ae0b025b
> Fix broken map downloading

- DXMainClient/DXGUI/Generic/GameInProgressWindow.cs
https://github.com/CnCNet/xna-cncnet-client/pull/688/files#diff-f0e518858928da27479a9192f39d5f11357c7d0aa101408e3f8ee62be8eb75c8R168
```diff
-#if ARES
+if (ClientConfiguration.Instance.ClientGameType == ClientType.YR)
```
> Fix broken screenshot processing for Ares

- DXMainClient/DXGUI/Multiplayer/LANLobby.cs
- DXMainClient/Online/CnCNetManager.cs
> Furtherly fix inconsistent color names

- DXMainClient/DXGUI/Generic/MainMenu.cs
> Fall back to legacy background music loading on failure

- ClientGUI/ICompositeControl.cs
- ClientGUI/INItializableWindow.cs
- ClientGUI/Parser.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CoopBriefingBox.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
- Docs/INISystem.md
> Implement composite controls support and customizable briefing font index
