CnCNet/xna-cncnet-client

- ClientCore/ClientConfiguration.cs
- DTAConfig/DirectDrawWrapper.cs
- DTAConfig/DisplayOptionsPanel.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- Due to an oversight, random side selectors were not properly unselected if changing to a map where they were unavailable. Now the interactions with disallowed side logic should work properly under all circumstances.
- Allow changing the text displayed on the item in client resolution dropdown that is designated as recommended resolution. By default this displays '(recommended)', which is way too big to fit in the dropdown with the larger font used in most YR mods - changing it to '(default)' leaves enough space. Issues like this can potentially crop up elsewhere in the client as well, and treating them all as special cases like this might not be the best course of action. Would probably warrant further discussion on how to approach the said problems, or if even should at all.
- A simple …
> A small random side selectors fix & couple of other changes.

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/PlayerListBox.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Online/ChannelUser.cs
- DXMainClient/Online/IRCUser.cs
* Currently highlights friends in the online box with a star
> Highlight friends in the online list

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
Fixes a problem introduced in commit aa6faa8002575d7b0ee4132ca7ee0bdc937ea704 included in PR #87 that would sometimes cause the client to freeze when searching for maps.
Long story short, when doing code refactoring to get rid of the 'unnecessary' counter variable, I somehow completely failed to register that just flat-out changing it to use the loop counter completely changes how the whole thing works when searching maps, as it skips pretty much the entire loop if map's name doesn't contain the search string and previously the counter would only get incremented if it didn't skip. Trying to get rid of the counter variable turned out to be a mostly moot point too, since it ended up needing an extra one regardless.
I did keep the for-loop implementation rather than revert back, however, …
> Bugfix for a client freeze introduced by the recent changes to map listing in game lobby.

- BuildScripts/Build.bat
- BuildScripts/FindMSBuild.bat
- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
Game room channels will now utilize postfixed main game lobby name instead of one generated from short game name and cncnet prefix. This change is meant to make game room channels inline with those mods that don't use #cncnet-[short game name] naming template.
Edit: now that VS2019 is out I edited buildscripts to be able to use it's MSBuild. Resulting binaries are proven to be working on XP.
> Fix game channel naming; support VS2019

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
- DXMainClient/DXGUI/Multiplayer/PlayerListBox.cs
- DXMainClient/Online/ChatMessage.cs
- DXMainClient/Online/CnCNetManager.cs
- DXMainClient/Online/Connection.cs
- DXMainClient/Online/IConnectionManager.cs
These changes address issues #82, #85 and #86. 
The fix for #82 comes with a small caveat in that it will only bypass the ignore list (and likewise disables the block functionality in context menu) for admins on the channels themselves where the said users are admins - it won't extend to other channels and private messaging. It could probably in theory be extended to apply to admins from all connected channels and even in private messaging, but that would probably require considerable amount of extra work, especially for private messages which do not really know anything about channels or admins.
The other changes are more complementary, allowing the client to more reliably adjust user information and reflect the changes in the player list box.
> Collection of fixes / improvements to CnCNet / IRC functionality

- DXMainClient/Online/Connection.cs
Fixes scenario where ident was truncated due to not taking into account the prepended game and full stop.
> Fix truncated ident

- DXMainClient/DXGUI/Generic/LoadingScreen.cs
- DXMainClient/DXGUI/Generic/TopBar.cs
Options can now be used from anywhere by clicking a button on topbar (or F12 hotkey). Tested to work with custom components on DTA installation. Upon entering the options menu all topbar buttons lock for user to explicitly confirm or discard option changes.
> Add options button at top bar

- ClientCore/ProgramConstants.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/Domain/Multiplayer/PlayerInfo.cs
This feature is based on a suggestion from players. Essentially an invisible-by-default (must be made visible through the UI INI system) checkbox that if toggled on, marks the player as with 'auto-ready' status which means that their actual ready status is not revoked under any circumstances until after the checkbox is unticked (unticking itself won't remove it, though). This piggybacks on existing messaging between players and game host, but since LAN game variant breaks compatibility and CnCNet one would otherwise be susceptible to sync problems, the protocol versions have been incremented as well. Default position of the checkbox is equivalent to where the 'Lock Game' button appears for game hosts.
Isn't marked as draft, but still open for discussion / scrutiny.
> Auto-ready checkbox for multiplayer game lobbies.

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyCheckBox.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyDropDown.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
The spam was caused by an improper fix to another issue of game settings being carried over from the game in which you wasn't the host.
> Fix "The game host has..." spam on map change

- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
Before the fix if you changed the dropdown value, then answered "No" when asked to restart, then opened the options menu again the dropdown would reset to current resolution and not the saved one, which could result in an unintended behavior of setting fullscreen resolution different from the real fullscreen resolution.
> Fix client resolution dropdown using the current res. instead of the saved one

- DXMainClient/Domain/Multiplayer/MapLoader.cs
Allows modders to pre-declare game modes in MPMaps.ini using GameModes list. Primary use-case of this would be to pre-determine the order of the game modes list displayed in the game lobby dropdown. Normally this would be achievable by simply adjusting the map list order, but there are specific conditions (most of which are admittedly rarely encountered) under which this is not possible. One example would be game modes that use subsets of maps from other game modes, which could result in an undesirable game modes list order if determined solely by map order. 
Some notes:
- I determined pre-declaring would be much less convoluted than trying to alter list order, especially the dropdown one directly after the fact, hence the chosen approach here.
- The pre-declared game modes list does not …
> Allow pre-declaring game modes in MPMaps.ini.

- DXMainClient/Properties/app.manifest
When High DPI is set, e.g. 125%
both DTA client and the game will be resized to a bad size, which sometimes causes the game failed to be started.
Example:
1920x1080 monitor with 125% DPI settings, which is the default setting on a 15.6 inch laptop.
The game will be resized to 1536x768 and then failed to start because the graphic card doesn't support this strange resolution.
By changing the manifest file this issue can be solved.
Note: although user can change the compatibility settings on Windows, but that is not a nice way. The issue should be solved directly, i.e this pull request.
> Fix High DPI issue

- DXMainClient/Online/Channel.cs
Addresses a minor issue where current client user's admin status in client was not updated properly if it was changed after joining the channel but before receiving channel user info (f.ex when being the first user to join an unregistered IRC channel).
> Set admin status on existing users upon receiving channel user list

- DXMainClient/Domain/Multiplayer/Map.cs
Restores the previous behaviour where first letter of game modes listed in custom maps was automatically capitalized and whitespace around it was ignored.
> A fix to custom map game mode name capitalization

- DXMainClient/Online/FileHashCalculator.cs
- Can now set `CalculateGameExeHash` under `[Settings]` in `FHCConfig.ini` to false to disable calculating hash for game executable file.
- Changes to `FHCConfig.ini` parsing:
- Now supports proper INI format (key=value) when parsing `[FilenameList]`. Old format (key only) is still supported for backwards compatibility.
- `INI\Map Code\GlobalCode.ini` is no longer added to the list of filenames parsed from the config on YRRelease build as an arbitrary exception.
- The 'hardcoded' list of files (client & game executables etc) now have their hashes logged as well.
> A number of proposed improvements & fixes to FileHashCalculator

- DXMainClient/Startup.cs
Have seen the hardware info (Win32_Processor->Name especially) contain excessive whitespace characters on some systems, that is better off trimmed out for readability.
> Remove unnecessary whitespaces from hardware info logging

- ClientGUI/ToolTip.cs
- ClientGUI/XNALinkButton.cs
- DTAConfig/OptionPanels/ComponentsPanel.cs
- DTAConfig/OptionPanels/UpdaterOptionsPanel.cs
- DTAConfig/OptionPanels/XNAOptionsPanel.cs
- DTAConfig/OptionsWindow.cs
- DXMainClient/DXGUI/Generic/MainMenu.cs
- DXMainClient/DXGUI/Generic/TopBar.cs
- Custom component button text now retains file size information even if download is canceled or unsuccessful.
- Options button in top bar will now be disabled if options window is open. This comes with minor graphical issues due to pressing the Options button altering its own AllowClick property. https://github.com/Rampastring/Rampastring.XNAUI/pull/5 contains a proposed fix to these graphical issues.
- Top bar buttons and main menu hotkeys are now disabled while updater window is open. Disabling hotkeys is not currently possible without just outright unsetting them, so there is potentially some room for improvement here. Also renders #134 incompatible and obsolete.
- Top bar status text won't be changed on disconnect from CnCNet if you have LAN (game) lobby currently open.
- Tooltips …
> Fixes to various UI-related problems

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/Domain/Multiplayer/GameMode.cs
- DXMainClient/Domain/Multiplayer/PlayerHouseInfo.cs
As requested by @Crimsonum you can now use `DisallowedPlayerSides` in game mode definitions. The usage is the same as with coop INI tag. Need investigation on how it would work with random selectors.
> Allow to disable sides per game mode

- ClientCore/CnCNet5/NameValidator.cs
- DTAConfig/OptionPanels/GameOptionsPanel.cs
- DXMainClient/DXGUI/GameClass.cs
Unifies the validation of player nickname on client startup and when saving settings. Also fixes an error with saving settings where it previously wouldn't save the cleaned up nickname to settings INI, instead using raw text from the player name textbox.
This validation now uses same list of allowed characters as the name check upon attempt to connect to CnCNet, but it won't check for offensive words nor it will remove starting dashes / numbers. If such functionality is desirable, it could be added but I didn't deem it worthwhile.
> Improve player nickname validation on startup & on saving settings

- ClientCore/ClientCore.csproj
- DXMainClient/Domain/Multiplayer/MapPreviewExtractor.cs
- DXMainClient/Domain/Multiplayer/MiniLZO.cs
- Fix decompression code to not fail on data that contains padding.
- Remove obsolete reference to MapThumbnailExtractor.dll from ClientCore.
- Comment out unreferenced labels in MiniLZO that were generating warnings.
> Fixup to map preview extractor rework

- README.md
* Updated readme with following links since old ones were outdated and getting MXA from the code archive was pretty convoluted:
* [Installing XNA for Visual Studio 2019](http://flatredball.com/visual-studio-2019-xna-setup/)
* [Installing XNA for Visual Studio 2017](http://flatredball.com/visual-studio-2017-xna-setup/)
* Mentioned MSBuild as not officially supported way of building the client since I added support for it some time ago.
> Update build instructions with better guides; mention MSBuild support

- DXMainClient/Online/Connection.cs
Thanks for your great work. I've made some modification about the process of connection to the Lobby servers. Please review and test it. Thank you.
1. Get all IP addresses of servers by resolving the hostname.
2. Test the latency to the servers and store them in a list.
3. If the latency is greater than 400 ms, ignore the server.
4. Sort the list and connect to the servers one by one.
1. Find the closest and reachable server in few seconds.
2. Connect to all servers bound to one domain name.
1. Resolve #141 .
At 10:16 PM 4/17/2020, there are 843 players on the server.
<details>
<summary>client.log</summary>
<pre>
...
17.04. 22:16:59.701    Writing settings INI.
17.04. 22:16:59.739    Attempting to DNS resolve GameSurge (irc.gamesurge.net).
17.04. 22:16:59.760    Attempting to DNS resolve …
> Added DNS resolution and latency test for the Lobby servers.

- ClientCore/ClientConfiguration.cs
- DXMainClient/DXGUI/Generic/GameInProgressWindow.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/PreStartup.cs
- DXMainClient/Startup.cs
All functionality changes below only apply to `AresRelease` and `AresDebug` configurations. Sole exception is that the graphics mode reset hack in `GameInProgressWindow.HandleGameProcessExited` was moved so that the code executes before there's any chance for the method to exit. Previously if deleting the log files on game startup failed for any reason, this reset hack wouldn't be applied on game exit, which didn't seem like intended behaviour.
- Client will now prune Ares debug log files & directories on startup. Any files that were created at least 7 days ago will be deleted and any directories that are empty after deleting files are also removed. The time threshold could be made customizable if a good enough reason to allow it comes up, but I could not think of any.
- Moved …
> Features / improvements for Ares build of the client.

- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
- DXMainClient/Domain/Multiplayer/Map.cs
Adds support for drawing extra textures on the map preview. Example:
Works by adding one or more of the following entries under a map's section in MPMaps.ini:
`ExtraTextureN=texture_file_name.png,x_coord,y_coord`
The x_coord and y_coord point to tiles on the map and can be taken directly from FinalSun.
For example, for the result in the image we added an `oilrefn.png` texture to the `Resources` directory in DTA and added this code to the map's section in MPMaps.ini:
```ini
ExtraTexture0=oilrefn.png,93,111
ExtraTexture1=oilrefn.png,113,144
ExtraTexture2=oilrefn.png,168,150
ExtraTexture3=oilrefn.png,150,117
ExtraTexture4=oilrefn.png,157,180
ExtraTexture5=oilrefn.png,134,222
ExtraTexture6=oilrefn.png,97,195
ExtraTexture7=oilrefn.png,104,82
ExtraTexture8=oilrefn.png,113,46 …
```
> Add support for drawing extra textures on the map preview

- ClientCore/ClientConfiguration.cs
- DXMainClient/DXGUI/Generic/MainMenu.cs
The new INI key
```ini
ForbiddenFiles=file1.txt,path/to/file2.txt,...
```
defined under `[Settings]` section of `ClientDefinitions.ini` can now be used to list files that are interfering with the mods functionality and should be removed. Any of those files would be mentioned in the message if they are present.
For TS build there is a custom message implemented that explains what the standalone mod is and that the user needs to install it in an empty folder, not on top of TS (because for some reason not all users read the installation instructions).
Closes #193.
> Implement interfering files detection

- ClientCore/ClientConfiguration.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/Domain/Multiplayer/PlayerHouseInfo.cs
`InternalSideIndices` (in `GameOptions.ini`, `[General]` section) is used to override default side IDs with the ones defined in lookup string. It's also now possible to override the side for spectator (and thus supply custom music, sidebar etc.) via explicitly specifying random side index via `SpectatorInternalSideIndex`, for example:
```ini
Sides=USA,United Kingdom,France...
InternalSideIds=0,4,2,...
SpectatorInternalSideId=16
```
> Reimplement InternalSideIndices and SpectatorInternalSideIndex GameOptions.ini keys

- ClientGUI/UIDesignConstants.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetGameLoadingLobby.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/GameCreationWindow.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/TunnelListBox.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/TunnelSelectionWindow.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
**TunnelSelectionWindow:**
- Add Cancel button that can be used to exit the window without applying changes.
- Apply button is disabled when currently selected tunnel is the original one.
- Tunnel lists scrolls to the selected tunnel on opening the window.
- Less cramped control spacing.
**GameCreationWindow:**
- Improve control spacing, especially regarding the buttons & bottom edge of the window.
- Set window width based on width of TunnelListBox and use global constants for control positions & sizes where possible.
- Set window height based on contents.
- Set names for controls to allow adjusting attributes from INI if needed.
Additionally `TunnelListBox` default height is now set to better match the contents and the way listbox scrolling currently works.
Main reason for changing …
> Improvements to TunnelSelectionWindow & GameCreationWindow

- DXMainClient/Online/Connection.cs
If the generic host is resolved as one of the explicit hosts, the server
will only be tried with the generic 6667 port instead of the
server-specific port values, due to the duplicate-checker code filtering
out the explicit host since it's DNS record returns after the generic
one. Placing the generic DNS record as last ensures that all specific
hosts will be resolved beforehand and allows connections in cases
where port 6667 is unreachable due to a network issue.
Fixes #208
> Resolve the generic hostname last.

- ClientCore/Settings/UserINISettings.cs
- ClientGUI/DarkeningPanel.cs
- DXMainClient/DXGUI/Generic/GameInProgressWindow.cs
- DXMainClient/DXGUI/Generic/MainMenuDarkeningPanel.cs
This PR does three things:
1) Makes client FPS user-configurable through `[Video] ClientFPS=`. Defaults to 60. This can be useful for users that have high refresh rate monitors and for people who want to lower the client's CPU usage at the expense of input smoothness.
2) Fixes MainMenuDarkeningPanel's alpha rate so it does not depend on the client's frame rate
3) Normalizes the alpha rate to be the same for MainMenuDarkeningPanel and the common DarkeningPanel
> Make client FPS user-configurable

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
Auto-ready checkbox, when toggled on, used to keep players' ready status on even while they were in-game. With this fix, the status should be stripped when starting a game but re-instated after exiting the game.
> Fix auto-ready option keeping ready status on even while in-game

- DTAConfig/OptionPanels/CnCNetOptionsPanel.cs
- DXMainClient/DXGUI/Generic/LoadingScreen.cs
- DXMainClient/DXGUI/Generic/MainMenu.cs
- DXMainClient/Domain/DiscordHandler.cs
- Remove unnecessary using statements.
- Remove unnecessary update method override.
- Do not require restart when changing Discord integration setting.
> DiscordHandler cleanup.

- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
- DXMainClient/Domain/Multiplayer/Map.cs
- Allow defining map tile level as additional, optional comma-separated value for both ExtraTextureN & WaypointN.
- Draw ExtraTextures that overlap with MapPreviewBox border over the border.
For an example:
```
Waypoint0=92181,0
ExtraTexture0=tech-oil.png,183,79,4
```
> Map preview box improvements.

- DXMainClient/DXGUI/Multiplayer/GameInformationPanel.cs
- DXMainClient/DXGUI/Multiplayer/GameListBox.cs
As the title says, fixes the game information panel not showing up with latest XNAUI by making the game information panel a child of the CnCNet / LAN lobby instead of the game list box.
I've confirmed the fix to work properly in DTA's fork of the client, but it's best to test it before merging anyway in case I made some mistake in porting over the code.
> Fix game information panel not showing up with latest XNAUI

- DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/RecentPlayerTable.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Online/CnCNetUserData.cs
- DXMainClient/Online/RecentPlayer.cs
When a game starts, all players will be logged. In the PM window, there will be a tab for recent players, listing their names, the name of the game you played with them in, and when the game was played. The list will be ordered from newest to oldest. The list will only show the last 50 players. All right-click options for each player in this list should work like any other player list in this window.
The main purpose is to capture recent players so that you can add them to your friends list afterwards, if desired.
> Recent players list

- DXMainClient/DXGUI/Multiplayer/ChatListBox.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/PlayerContextMenu.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/PlayerMessageContextMenu.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/RecentPlayerTable.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Online/ChatMessage.cs
Right click context menu for player-sent messages in the cncnet main lobby.
For now, this uses the existing functionality of the current player right-click context menu. However, it is a derived class leaving it open to other future menu options.
> CnCNetLobby message right click context menu

- DXMainClient/DXGUI/Multiplayer/CnCNet/LoadOrSaveGameOptionPresetWindow.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Domain/Multiplayer/GameOptionPresets.cs
The ability to save and load game options already exists via a "slash" command in the game chat. This simply exposes them to the UI. This menu exists in the GameLobbyBase thus also enables them for skirmish.
> Expose ability to load/save game options in UI

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
After returning from a  game, the player options drop downs weren't respecting the "forced" options.
> Keep forced player options disabled after game return

- DXMainClient/DXGUI/Generic/LoadingScreen.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
- DXMainClient/Domain/Multiplayer/MapLoader.cs
Maps were being deleted properly, but the UI wasn't being updated to show it. If the user restarted their client, the map would no longer be there.
> Fix issue with deleting custom map

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
If you select a map in the list as the host, the game mode is always Battle for guests.
> Fix issue with game modes not being handled on guest end

- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
Now there will always be a space between the team name and the player name.
DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
```cs
text = teamIds[pInfo.TeamId] + text;
```
DXMainClient/DXGUI/Multiplayer/GameLobby/PlayerLocationIndicator.cs
```cs
text = pInfo.TeamId > 0 ? pInfo.Name + " " + teamIds[pInfo.TeamId] : pInfo.Name;
```
> Fix the inconsistency of the map indicator

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/TunnelSelectionWindow.cs
- DXMainClient/DXGUI/Multiplayer/GameFiltersPanel.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/PreStartup.cs
- DXMainClient/Program.cs
- Localization/TranslationTable.cs
There are four strings in the source code that contains the semi-colon(`;`) character.
When generating the stub file, this character is written to the .ini file.
But when the .ini file be loaded again, everything behind this character is regarded as a comment, i.e. be ignored.
(P.S. it seems that most C# library that handles .ini file would not throw an exception if some special characters are in the value. It should throws.)
In this PR I replace the `;` with `.` for these four strings.
Besides, some label name contains space or does not have the expected prefix (although it still works). These names are now get corrected.
> Fix my mistake in literal string translation

- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
```cs
public override int GetHashCode()
{
return new { Width, Height }.GetHashCode();
// return Width - Height;
}
```
It follows the best practice at: https://stackoverflow.com/a/4630550.
> Fix incorrect hash code implementation

- ClientCore/CCIniFile.cs
- ClientGUI/INItializableWindow.cs
- ClientGUI/XNAClientButton.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/Resources/DTA/GlobalThemeSettings.ini
- Docs/INISystem.md
- Improve ini config file locating
- This slightly improves the backwards compatibility of the new INItializableWindow implementation.
- With the initial INItializableWindow updates, there seemed to be no inheritance of which ini config file to load for a given class implementing INItializableWindow. If it has an override ini name, it would attempt to use it, but not fall back to the name of the control itself, which could be the parent class' name.
- Make BasedOn a list for multi inheritance
- Fix missing toggle fav map event
- Add starting documentation for INI system
- Fix bug in XNAClientButton
> Post v6 updates

- ClientCore/Settings/UserINISettings.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
This removes the default sorting of maps alphabetically and instead adds a sort button to the left of the game mode drop down list.
The list is not sorted by default. The setting for the sort selection is stored in user ini settings.
> Allow option to sort map list

- ClientCore/Settings/UserINISettings.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MapPreviewBox.cs
- DXMainClient/Domain/Multiplayer/Map.cs
Client now reads an additional optional boolean value from maps INI for extra textures which tells if it is toggleable or not.
f.ex
`ExtraTexture0=tech-oil.png,59,86,4,true`
If currently selected map has any toggleable textures on it, an additional context menu option and button is shown for toggling these textures on / off - this state is saved in options INI and retained throughout the game lobbies / sessions.
I initially wanted to condense the favourite button and this into something like the Load / Save one for game options but decided against this as I figured some people probably like seeing the favourite status at a glance.
> Toggleable map preview box ExtraTextures

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/Domain/Multiplayer/CnCNet/MapSharer.cs
- Add a command to download a map by hash: `/downloadmap HASH`
- Allow users to specify a filename after the hash, e.g. `/downloadmap HASH [2] My Battle Map`
- Fix a bug where renaming unzipped map files would cause a crash if the `.map` filename already exists.
- Relocate the file renaming to occur after we check that the file was successfully unzipped.
Users and devs can find map IDs using this URL template `http://mapdb.cncnet.org/search.php?game=GAME_ID&search=MAP_NAME_SEARCH_STRING`
Issue: https://github.com/CnCNet/xna-cncnet-client/issues/350
> #350: Add a command to download a map via lobby chat

- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/Domain/Multiplayer/PlayerExtraOptions.cs
In `GameLobbyBase.cs`:
```cs
protected PlayerExtraOptions GetPlayerExtraOptions() =>
PlayerExtraOptionsPanel == null ? new PlayerExtraOptions() : PlayerExtraOptionsPanel.GetPlayerExtraOptions();
```
And in `PlayerExtraOptions.cs`:
```cs
public List<TeamStartMapping> TeamStartMappings { get; set; }  // this is by default null
```
Which causes a crash of a null pointer at `PlayerExtraOptions.ToString()`, where:
```cs
TeamStartMapping.ToListString(TeamStartMappings) // TeamStartMappings is null, while ToListString() crash on null
```
-----------------
Also, in `MultiplayerGameLobby.cs`:
```cs
PlayerExtraOptionsPanel.SetIsHost(isHost);
```
`PlayerExtraOptionsPanel` can be null.
> Fix crashes caused by null PlayerExtraOptionsPanel

- .gitignore
- Directory.Build.props
With this, I can create YR specific build props file to copy in resources from the YR client repo so that launching the xna client is done in the YR context.
> Allow optional import of game specific build props

- DXMainClient/DXGUI/Generic/TopBar.cs
Hello!
If the time format of the current locale contains an AM/PM designator, it will go beyond the right border of the window.
I tried to remove the AM/PM designator; @Rans4ckeR reviewed my code and said:
> The application should use correct localization, so en-US systems should display AM/PM.
> A proper solution is to update the layout instead. For example by changing the placeholder like this:
> 
> ```C#
> lblTime.Text = new DateTime(1, 1, 1, 23, 59, 59).ToLongTimeString();
> ```
> 
> *source: https://github.com/CnCNet/xna-cncnet-client/pull/366#pullrequestreview-1103272340*
That's better, isn't it? So I make this PR. 
Here is the screenshot:
This PR will close #366 if gets merged.
> Make locale-aware time fully displayed in TopBar to prevent the string from going beyond the border

- Localization/Localization.csproj
In file `Startup.cs`:
```cs
string themePath = ClientConfiguration.Instance.GetThemePath(UserINISettings.Instance.ClientTheme);
if (themePath == null)
{
themePath = ClientConfiguration.Instance.GetThemeInfoFromIndex(0)[1];
}
ProgramConstants.RESOURCES_DIR = SafePath.CombineDirectoryPath(ProgramConstants.BASE_RESOURCE_PATH, themePath);
```
`themePath` could be `string.Empty`. (e.g. Mental Omega)
And old version of Rampastring.Tools will mistakenly return `"\\"` as the combined dir path to `ProgramConstants.RESOURCES_DIR`, which has been fixed by https://github.com/Rampastring/Rampastring.Tools/pull/7
And this PR upgrades the dependency to solve this bug.
------------------------------
P.S. I don't know why the dependency of `Rampastring.Tools` only appears in `Localization` project and …
> Update Rampastring.Tools to fix crashes on empty theme folder

- ClientCore/ClientConfiguration.cs
- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
This was requested by CCHyper of Tiberian Odyssey, as they say they do not need this feature.
> Make copying of Language.dll in TS builds optional

- DXMainClient/Online/CnCNetManager.cs
- DXMainClient/Online/Connection.cs
- DXMainClient/Online/IConnectionManager.cs
I got the following messages when joining the lobby in Mental Omega 3.3.6 with Chinese language pack:
```
[0:00 AM] 正在与 CnCNet 建立连接...
[0:00 AM] 当前网络质量较好的服务器数量：10
```
The English translation of the above messages is:
```
[0:00 AM] Connecting to CnCNet...
[0:00 AM] At present, the number of servers with better network quality: 10
```
The second message is wrong. Let me explain.
I didn't write the code to display a message about the number of lobby servers. That Chinese message was added by the friends of the translation group. I *guess* that they may have misunderstood the code, thinking that the return value of the "[```GetServerListSortedByLatency()```](https://github.com/CnCNet/xna-cncnet-client/blob/3f24248a251cf0032f7b3fd92080b7980575bf3a/DXMainClient/Online/Connection.cs#L328-L490)" …
> Add log and client output for lobby server latency test result

- ClientCore/ClientConfiguration.cs
- DXMainClient/Domain/MainClientConstants.cs
- DXMainClient/Domain/Multiplayer/Map.cs
This PR adds optional, configurable support for displaying starting locations of players in Red Alert 1 and Tiberian Dawn maps correctly.
These games use non-isometric cells, which requires some changes to the cell math for figuring out the pixel coordinates of starting locations.
They also have a slightly different map format when it comes to specifying the size of the map, which required changes to the map size parsing code.
To support these features without making TS/YR support more complicated, two new keys were introduced to `ClientDefinitions.ini`:
```cs
[Settings]
UseIsometricCells=
WaypointCoefficient=
```
`WaypointCoefficient` is only used when calculating waypoint positions for RA and TD. `UseIsometricCells` defines whether the use TS/YR or RA1 logic for parsing the map size and …
> Implement support for parsing and displaying starting positions of Red Alert 1 and Tiberian Dawn maps, with non-isometric cells

- DXMainClient/DXGUI/Generic/MainMenu.cs
Fixes #399
Also fixes the 2nd stage updater unable to update the music file on linux as it complains about the file still being in use even after the client has exited.
> 399-the-main-menu-music-track-can-be-heard-after-the-client-closes

- DTAConfig/OptionPanels/AudioOptionsPanel.cs
- DTAConfig/OptionPanels/GameOptionsPanel.cs
Fixes #438
XNATrackbar.ValueChanged event is not triggered when the initial value is set to 0 since it already is 0. Set the label default value to 0 to match the default XNATrackbar value.
> 438-volume-showing-as-10-even-though-its-set-to-0

- ClientGUI/GameProcessLogic.cs
```cs
var gameProcess = Process.Start(new ProcessStartInfo(gameFileInfo.FullName, arguments));
...
try
{
gameProcess.Start();
```
`Start()` is executed twice here.
> Don't start the process twice

- DXMainClient/Online/FileHashCalculator.cs
Crashes on New LAN Game.
Fix: check `Directory.Exists(ClientConfiguration.Instance.TranslationsFolderPath)` first.
```txt
02.04. 09:51:41.922    KABOOOOOOM!!! Info:
02.04. 09:51:41.922    Type: System.IO.DirectoryNotFoundException
02.04. 09:51:41.923    Message: Could not find a part of the path 'F:\Mental Omega Dev\Resources\Translations'.
02.04. 09:51:41.923    Source: System.Private.CoreLib
02.04. 09:51:41.923    TargetSite.Name: CreateDirectoryHandle
02.04. 09:51:41.956    Stacktrace:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
at System.IO.Enumeration.FileSystemEnumerator`1.Init()
at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean …
```
> Fix crashes when translation folder does not exist

- Docs/Migration-INI.md
- Docs/Migration.md
This PR extends the migration guide with a step-by-step example INI configuration migration. It's aimed at YR modders, but most steps are applicable to any game using this client.
> INI migration guide

- ClientCore/SavedGameManager.cs
- ClientCore/Statistics/GameParsers/LogFileStatisticsParser.cs
- ClientCore/Statistics/StatisticsManager.cs
- ClientGUI/GameProcessLogic.cs
- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
- DTAConfig/OptionsWindow.cs
- DXMainClient/DXGUI/GameClass.cs
- DXMainClient/DXGUI/Generic/GameInProgressWindow.cs
- DXMainClient/DXGUI/Generic/MainMenu.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
- DXMainClient/DXGUI/Multiplayer/LANGameLoadingLobby.cs
- DXMainClient/DXGUI/Multiplayer/LANLobby.cs
- DXMainClient/Domain/Multiplayer/CnCNet/CnCNetTunnel.cs
- DXMainClient/Domain/Multiplayer/CnCNet/MapSharer.cs
- DXMainClient/Domain/Multiplayer/CnCNet/TunnelHandler.cs
- DXMainClient/Domain/Multiplayer/LAN/LANPlayerInfo.cs
- DXMainClient/Domain/Multiplayer/Map.cs
- DXMainClient/Domain/Multiplayer/MapPreviewExtractor.cs
- DXMainClient/Domain/SavedGame.cs
- DXMainClient/Online/CnCNetUserData.cs
- DXMainClient/Online/Connection.cs
- DXMainClient/PreStartup.cs
- DXMainClient/Startup.cs
```diff
-Logger.Log(ex.Message);
+Logger.Log(ex.ToString());
```
`ex.ToString()` contains stack trace. Currently the client will not record stack trace for non critical exceptions and it's bad.
For those `ex.Message` acting as UI strings, they are untouched
> Write detailed exception message to log

- ClientCore/ProgramConstants.cs
- DXMainClient/DXGUI/GameClass.cs
- DXMainClient/Domain/MainClientConstants.cs
- DXMainClient/PreStartup.cs
- DXMainClient/Program.cs
Fixes https://github.com/CnCNet/xna-cncnet-client/issues/458 in .NET 4.8.
This PR also moves DisplayErrorAction from ClientCore to DXMainClient because this is an GUI stuff.
For .NET 8.0:
- In Windows, there's always a black console window running dotnet.exe. This is because the window can not be hidden if ShellExecute is used, while ShellExecute is an requirement of verb runas. So in .NET 8.0 there will be no automatic evaluation because a black console window is more annoying. Users should run the launcher as admin instead.
- In non-Windows, since when this error happens, the client has no privilege to write text files on game folder (the logger cannot be initialized then), a text file xna-cncnet-client-error.txt is created in temp, in order to show error dialog.
Thus, .NET 8.0 clients …
> Fix privileges evaluation

- ClientCore/ClientConfiguration.cs
- DTAConfig/OptionPanels/CnCNetOptionsPanel.cs
- DXMainClient/DXGUI/Generic/MainMenu.cs
- DXMainClient/Domain/DiscordHandler.cs
- DXMainClient/Domain/MainClientConstants.cs
- DXMainClient/Domain/Multiplayer/CnCNet/CnCNetPlayerCountTask.cs
- DXMainClient/Domain/Multiplayer/CnCNet/MapSharer.cs
- DXMainClient/Domain/Multiplayer/CnCNet/TunnelHandler.cs
- DXMainClient/Online/Connection.cs
- DXMainClient/Online/Server.cs
- DXMainClient/Resources/DTA/NetworkDefinitions.ini
Fixes #479 and #489
This PR removes all servers but `irc.gamesurge.net` --- the rest domains are (almost) duplicated. See #489 for more details.
This PR defines a new configuration file `NetworkDefinitions.ini`. This file is optional, so if it is missing everything goes well as if this PR were not merged -- except removing all servers but `irc.gamesurge.net`
----
The following urls are configurable:
- http://cncnet.org/master-list
- http://api.cncnet.org/status
- http://mapdb.cncnet.org
- http://mapdb.cncnet.org/upload
Also, setting a url to empty means do not fetch these resources online. This is meaningful if either:
- someone publishes a mod only focusing on solo mission
- a user's Internet connection is partially unstable
Add an option `DisableDiscordIntegration` to enable Chinese …
> Make network servers configurable

- DXMainClient/DXGUI/Generic/CampaignSelector.cs
- DXMainClient/Domain/Mission.cs
Different parsing of duplicate entries in Battle.ini between the client and the game (Tiberian Sun) has led to the game crashing as the game sees duplicate entries as one entry, while the client sees them as separate entries. Separate entries are often used by modders to add separators to the mission list.
The game is not known to really use the campaign ID for much (only the "do you need GDI/Nod/Firestorm CD" check is known), so setting it to `-1` by default should do little harm. In case it does, there is now the possibility to manually override the campaign ID.
`-1` is interpreted by the game as `CAMPAIGN_NONE`, which allows playing with any CD.
This would also affect the game's "final campaign movie" logic (`FinalMovie=` in `Battle.ini`), but as far as I know, no distribution of TS, …
> Make CampaignID default to -1, with an optional override

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
This button is like a black sheep in the client configuration files. All buttons in the config files have `btn` in lower case, for example `btnLaunchGame`, but `BtnSaveLoadGameOptions` is an exception to this rule. It was a typo, I suppose.
After this PR config `GameLobbyBase.ini` should be modified to lower case `BtnSaveLoadGameOptions` to `btnSaveLoadGameOptions`, for example:
```diff
Before
-$CC05=BtnSaveLoadGameOptions:XNAClientButton
After
+$CC05=btnSaveLoadGameOptions:XNAClientButton
```
> Fix `BtnSaveLoadGameOptions` button naming

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
Suppose a player turns on the extra option panel, leave the lobby, and then re-join a lobby, the extra option panel is still turned on, instead of the default panel that displays players with their factions, colors, and locations. 
This current behavior might be non-straightforward to players -- panel that belongs to the parent should also be closed when the parent is closed. It might be better to auto close the extra option panel when user leaves the lobby.
> Close player extra option panel when leaving the lobby

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
Currently, previous map is only preserved if *both* game mode *and* map are identical before and after changes. So it won't work as people usually expected.
This PR corrects this behavior so that as long as there exists a `GameModeMap` whose map is identical before and after changes, regardless of the game mode, it would be selected. Note: if a `GameModeMap` matches both game mode and the map (i.e., switching to/from favorite map), it would have the top priority.
> Fix current selected map is not preserved during game mode changes

- DXMainClient/Program.cs
It should be a compiler error not a syntax error
[CS1029](https://learn.microsoft.com/dotnet/csharp/language-reference/compiler-messages/cs1029)
> make compiler error

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
Crash reproduce steps:
Apply the latest client binaries in develop branch to [cncnet-client-mod-base](https://github.com/Starkku/cncnet-client-mod-base) (commit: 2c24f91299be519dd0f98e56b7d8f0509c7bff9c) and run the client. 
```
27.04. 08:06:18.404    KABOOOOOOM!!! Info:
27.04. 08:06:18.404    Type: System.NullReferenceException
27.04. 08:06:18.404    Message: Object reference not set to an instance of an object.
27.04. 08:06:18.419    Source: clientdx
27.04. 08:06:18.419    TargetSite.Name: DdCurrentChannel_SelectedIndexChanged
27.04. 08:06:18.419    Stacktrace:    at DTAClient.DXGUI.Multiplayer.CnCNet.CnCNetLobby.DdCurrentChannel_SelectedIndexChanged(Object sender, EventArgs e)
```
Issue reported by typhoon_4869_68340
This PR should fixes the issue
> Fix crash on null current chat channel

- Docs/Translation.md
Unlike other languages codes, there are two country-irrelevant language codes for Chinese: `zh-Hans` (Simplified Chinese, used in the mainland of China, Singapore, and Malaysia) and `zh-Hant` (Traditional Chinese, used in Chinese Hong Kong, Macao, and Taiwan). Although these two are regarded as Chinese variants, majority of the characters are different. 
Translators tend to explicitly differ Simplified Chinese and Traditional Chinese. However, some translators use a wrong language code (e.g., `zh_cn`, where the underscore is unexpected), or a county-specific language code (e.g., `zh-cn`, ignoring Singapore users). This makes me feel it is necessary to add Chinese language code examples so they could just follow the best practice.
The following list demonstrates the language code …
> Add Chinese language code examples to translation documentation

- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
- DTAConfig/ScreenResolution.cs
- DXMainClient/DXGUI/GameClass.cs
- DXMainClient/Program.cs
- DXMainClient/Startup.cs
Fixes #359.
This PR includes the following changes:
- Class `DTAConfig.OptionPanels.DisplayOptionsPanel.ScreenResolution` has been refactored as `DTAConfig.ScreenResolution`. This is necessary to simplify the handling work about the ultra resolution limitation.
- Support for ultra resolutions (where either the width or height exceeds 3840 pixels) across DX and GL builds
- Prevent XNA builds from listing or applying ultra resolutions.
- Add additional integer-scaled windowed client resolutions for recommended resolutions. (see the screenshot in the end)
- Previously, the UGL build does not declare high DPI awareness, which brings unnecessary blurry. It has been fixed.
- Previously, the UGL build fails to constraint the client resolution equaling desktop resolution on full screen mode. This …
> Refactor ScreenResolution and enable HiDef profile

- ClientCore/ProcessLauncher.cs
- ClientGUI/XNALinkButton.cs
Hello~
I think it will be great to enable the arguments configuration for the `ini` file. Then we can pass arguments like `-speedcontrol` to the executable when we click the `Campaign` button at here https://github.com/CnCNet/cncnet-yr-client-package/blob/develop/package/Resources/Allied%20Theme/ExtrasWindow.ini#L18 
Looking forward to any suggestions.
> Enable arguments passing for XNALinkButton URL

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameInformationPanel.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/LANLobby.cs
Previously, if a player does not select a map, it will either make the game room invisible (for CnCNet) or causes the client to crash (for LAN). Changing a game option when the map is deselected also causes the client to crash.
Related codes have been reworked, so that:
- A game room whose map is deselected is correctly shown in the list, instead of missing or a crash. 
- The change will be correctly updated to all players when the map is deselected and the host changes a game option, instead of a crash.
- The change will be correctly updated to all players when the host deselect a map, instead of a crash.
> Fix crash on empty map

- Docs/Migration.md
- Docs/Updater.md
- README.md
Fixes https://github.com/CnCNet/xna-cncnet-client/issues/539
Normalizes path separators as `/` to keep consistency among most `.md` documents
Suggest keeping `.pdf` files in documentation
Collapse some .NET 8 details.
> Correct paths and suggest keeping pdb files in doc

- ClientCore/I18N/Translation.cs
- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
Although the constructor `new CultureInfo(string)` is [defined](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=net-8.0#system-globalization-cultureinfo-ctor(system-string)) as case-insensitive, the client does not fully comply with this convention right now.
As a result, when translators created a folder named `zh-hans` (while the normalized name should be `zh-Hans`), the client will not be able to select this translation as the default.
This PR fixes this issue, allowing the folder name be case-insensitive.
> Ignore case when selecting default translation code

- Directory.Build.props
Currently, `ClientUpdater.xml` and `SecondStageUpdater.xml` are generated when building the client. This behavior was untouched when we merge `ClientUpdater` repo into this repo. However, since these two projects are tightly coupled with the client, same as `ClientCore` does, there should be no need to retain these XML files.
> Disable generating XML documentation files

- Directory.Packages.props
As warned by MSBuild, ImageSharp 2.1.7 has the following 4 vulnerabilities, especially the out-of-bounds write.
> D:\a\xna-cncnet-client\xna-cncnet-client\DXMainClient\DXMainClient.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 2.1.7 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-5x7m-6737-26cr
> D:\a\xna-cncnet-client\xna-cncnet-client\DXMainClient\DXMainClient.csproj : warning NU1903: Package 'SixLabors.ImageSharp' 2.1.7 has a known high severity vulnerability, https://github.com/advisories/GHSA-63p8-c4ww-9cg7
> D:\a\xna-cncnet-client\xna-cncnet-client\DXMainClient\DXMainClient.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 2.1.7 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-g85r-6x2q-45w7
> …
> Upgrade SixLabors.ImageSharp to 2.1.9

- Directory.Packages.props
Sometimes GitVersion causes GitHub action fails occasionally, for example, https://github.com/CnCNet/xna-cncnet-client/actions/runs/11033021431/job/30643231232?pr=557
```
C:\Users\runneradmin\.nuget\packages\gitversion.msbuild\5.11.1\tools\GitVersion.MsBuild.targets(13,9): error : IOException: The process cannot access the file 'D:\a\_temp\_runner_file_commands\set_env_1eb70c4f-ee40-4336-baf6-ec520a3b333f' because it is being used by another process. [D:\a\xna-cncnet-client\xna-cncnet-client\ClientUpdater\ClientUpdater.csproj::TargetFramework=net48]
```
The last version that supports .NET Framework 4.8 is `5.12.0`, while we are using `5.11.1`. Not sure whether this issue is fully solved in `5.12.0`, but upgrading to this last version released one and a half year ago should not bring …
> Upgrade GitVersion.MsBuild to 5.12.0

- DXMainClient/Domain/Multiplayer/CnCNet/CnCNetPlayerCountTask.cs
- DXMainClient/Domain/Multiplayer/CnCNet/ExtendedWebClient.cs
- DXMainClient/Domain/Multiplayer/CnCNet/MapSharer.cs
- DXMainClient/Domain/Multiplayer/CnCNet/TunnelHandler.cs
The web client was created by `new WebClient()` without assigning a timeout value. It seems that the default timeout value is undocumented, and the debugger told me the default value is 100000 ms (note: 100 seconds!) No wonder why some people with poor Internet condition complained about it takes too long to wait for their clients to initialize.
This PR proposed the following changes:
- By default, the timeout value would be 10 seconds instead of 100 seconds
- As an exception, the timeout value of uploading/downloading a map is set to 100 seconds
- Remove the obsolete `TWebClient` introduced 8 years ago ([here](https://github.com/CnCNet/xna-cncnet-client/commit/d33e7c2a3a55381d8dd98dc5bc9ee491af7e6575)) since `ExtendedWebClient` was introduced 6 years ago …
> Reduce default timeout to 10 seconds

- DXMainClient/PreStartup.cs
This PR prints detailed client version ("ProductVersion") in the log, for example, `2.12.0-feat-detailed-client-version.1+9.Branch.feat-detailed-client-version.Sha.54da550909971152332380ca79fe1b732501ec3a`. Containing the git commit should be extremely helpful to minimize the mess and determine the client version if a user uses a non-release build.
> Print detailed client version in the log

- ClientCore/ClientConfiguration.cs
- ClientCore/Settings/UserINISettings.cs
- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
- DTAConfig/ScreenResolution.cs
- DXMainClient/DXGUI/GameClass.cs
- DXMainClient/DXMainClient.csproj
- DXMainClient/Program.cs
- DXMainClient/app.PerMonitorV2.manifest
- DXMainClient/app.SystemAware.manifest
- Directory.Packages.props
This PR:
1. Adds integer scaling support for rendering the client. This feature is by default turned off.
2. Makes the client window resizable for DX and XNA builds if integer scaling is turned **ON**.
3. Improves 1.5x scaling for 1920x1080/1920x1200 if integer scaling is turned **OFF**.
4. Introduces some default options that can be defined in `[UserDefaults]` section in `ClientDefinitions.ini` file by modders.
5. Downgrades the DPI awareness from PerMonitorV2 to SystemAware for OGL builds to prevent weird GL window resizing when moving the client window between two monitors with different DPI settings. DX and XNA builds stay in PerMonitorV2. UGL build stays in SystemAware.
`1280x720` will be selected as the render resolution (if valid) if the window size is `1920x1080` (1.5x). Same for …
> Add integer scaling feature and make client window resizable

- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
There was a reported issue in the #support channel of Discord where someone's client was crashing while hosting a lan game as soon as another player joined. It happens when the "file hash" message is received from the joining user. When this happens, it attempts to find that player in their host's Player list. It attempts to set the `verified` property to `true` on that player. However, the client was not able to find the player in the list for some reason and thus a null pointer exception was being thrown.
I provided a temporary new exe to that person and they verified that they were able to play the game with fellow lan members without issue. I don't know if this change will cause any issues though...
> Fix a possible LAN game crash on an unexpected player name

- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetGameLoadingLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/LANGameLoadingLobby.cs
- DXMainClient/Online/FileHashCalculator.cs
- DXMainClient/Startup.cs
This PR reworks the file hash calculator to:
- Fix a bug introduced in https://github.com/CnCNet/xna-cncnet-client/pull/341/ (codes [here](https://github.com/SadPencil/xna-cncnet-client/blob/6426387f1c49b8c7a777974f317aa5dacaee5984/DXMainClient/Online/FileHashCalculator.cs#L122), diff [here](https://github.com/SadPencil/xna-cncnet-client/commit/6426387f1c49b8c7a777974f317aa5dacaee5984#diff-8b0a3b31ace8601b4fae1ee40f79eff20dcaf8b0382207d36b492f7845a85681R122)), where all files in "Map Code" and "Game Options" folders are not included. This bug should be a threat for anti-cheating detection.
TLDR: the bug is introduced because:
```csharp
string folderName = @"E:\SteamLibrary";
string fileName1 = Directory.GetFiles(folderName).First().Dump(); // "E:\SteamLibrary\libraryfolder.vdf"
string …
```
> Refactor calculating file hashes

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
When the number of players is 1, the random map will be assigned to any map, regardless of the max players of the map.
Used to randomly check maps.
> Randomize all maps when there is only one player

- DTAConfig/DirectDrawWrapper.cs
File.Delete() won't throw an error. But new FileInfo(path).IsReadOnly does
> Fix options cannot be saved when a renderer is not selected

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/LANLobby.cs
https://github.com/CnCNet/xna-cncnet-client/issues/602
> Fix pm window not being initialized for multiplayer game lobby

- SecondStageUpdater/Program.cs
After merging PR #590, not all cases of using links are covered, resulting in several bugs in various client-related programs, such as the [Client Launcher](https://github.com/CnCNet/dta-mg-client-launcher) (already [fixed](https://github.com/CnCNet/dta-mg-client-launcher/pull/17)) and the Second Stage Updater, because they can't replace files that have read-only property enabled.
The purpose of PR is to fix this bug for Second Stage Updater.
Example of bug:
> Fix readonly files can't be copied on the 2nd stage of the update

- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
While testing the TSC translation, I found a strange bug when not all text was translated for the TS compatibility fix. In message box code, description was split with `+` operator and `.L10N` doesn't affect all text. PR should fix this bug.
Bug example:
> Fix bug TS compatibility message box text

- DXMainClient/Online/FileHashCalculator.cs
Hey!
I'm using [cncnet-yr-client-package@`8645fa4`](https://github.com/CnCNet/cncnet-yr-client-package/tree/8645fa461c604b0f0c7545a44e9bdd475522d1f7). Today, I've gotten some "File xxx is supposed to but does not exist" messages. After debugging, I think the current implementation (#341 and #567) is a bit buggy, so I made this PR.
The correct result in the block:
| `filename` | `fileRelativePath` |
|:- |:- |
| `Allies Allowed.ini` | `Game Options\Allies Allowed.ini` |
| `No Dog Engi Eat.ini` | `Game Options\No Dog Engi Eat.ini` |
| `No Spawn Previews.ini` | `Game Options\No Spawn Previews.ini` |
| `No_France_No_Yuri.ini` | `Game Options\No_France_No_Yuri.ini` |
| `No_Spy.ini` | `Game Options\No_Spy.ini` |
| `RA2 Classic Mode.ini` | `Game Options\RA2 Classic Mode.ini` |
| `Yuri Rebalance …
> Fix incorrect hash calculation for files in nested directories

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
Not the most optimal but fast fix of the small issue that annoyed me for months.
Currently, if you turn on sorting of the map list in the skirmish lobby, select some map and restart the client, the map changes to a completely different one. If the sorting is off, selected map is kept between restarts correctly.
> Fix skirmish lobby selecting wrong map when the list is sorted

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
Fix for issue #597. When calling ShowMapList() or HideMapList() the labels are reloaded from the INI file which resets the text. The logic in ChangeMap() that updates the labels to the correct text has been extracted into a new function which is called after the INI resets and within ChangeMap().
> Fix map information labels not being updated in certain cases

- DXMainClient/PreStartup.cs
- DXMainClient/Startup.cs
This PR fixes two issues occuring after upgrading YR client to 8.65+ when running in Wine (Linux).
.NET Framework 4.8 version hangs in WMIC when generating online id. Changing from async function to a manual thread (like in CheckSystemSpecifications()) solves the issue.
.NET 8 version throws SecurityException which crashes the app when checking directory permissions. Catching the exception solves the issue.
From SteamOS/Linux user perspective it is easier to keep using Windows executables, which worked up until 2.11.0.0, so it would be nice if these fixes could be merged.
Thanks.
> Fix issues when running 2.11.0.0+ in Wine.

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
- DXMainClient/Domain/Multiplayer/GameMode.cs
Currently the only way to restrict side selection is via co-op map settings, game mode settings or game option checkboxes. This PR expands the way modders can restrict selection (only for game modes) for human players and computer players separately, using `DisallowedHumanPlayerSides` and `DisallowedComputerPlayerSides`.
Example usage in `INI/MPMaps.ini`:
```ini
[Standard]                          ; any game mode section
; (...)
DisallowedPlayerSides=7             ; already exists - disallow sides for all players
DisallowedHumanPlayerSides=1,2,3    ; new - disallow sides for human players only
DisallowedComputerPlayerSides=4,5,6 ; new - disallow sides for computer players only
```
> Allow disabling specific sides for human or AI players only

- DXMainClient/Domain/Multiplayer/MapLoader.cs
Had an "IndexOutOfRangeException" today on **localMapSHAs.Add(map.SHA1);** and I think this is the fix for it. 
I don't know anything when it comes to threading so hopefully one of the propeller heads around here can verify this.
> Fix concurrency issue in LoadCustomMaps by using a thread-safe collection

- ClientCore/ClientConfiguration.cs
- DXMainClient/PreStartup.cs
For #653 
Adds check for NetworkDefinitions.local.ini
The changes in PreStartup.cs are to fix the logging as the network definitions were loaded before the initial log file outputs.
So instead of:
10.02. 10:25:54.356    Loaded network definitions from NetworkDefinitions.local.ini (user override)
10.02. 10:25:54.361    ***Logfile for Yuri's Revenge client***
10.02. 10:25:54.387    Client version: 2025-02-05 develop@f11f56f
10.02. 10:25:54.387    2.11.0-beta.199+Branch.develop.Sha.f11f56f5a80f141faa998cf3566948afe5021d1c
10.02. 10:25:54.388    This is a development build of the client. Stability and reliability may not be fully guaranteed.
10.02. 10:25:54.389    Loading settings.
It will show:
10.02. 10:32:12.032    ***Logfile for CnCNet Client client***
10.02. 10:32:12.059    Client …
> Allow user-defined network settings via NetworkDefinitions.local.ini

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
Should fix auto ready issues as described here https://github.com/CnCNet/xna-cncnet-client/issues/664
https://github.com/user-attachments/assets/f6775b85-fa4e-45cb-a2cb-e16e0ff126ef
https://github.com/user-attachments/assets/0977ece5-6e14-4dd0-ae4f-9df159373e1c
https://github.com/user-attachments/assets/8218e980-907d-4392-869b-00f9fb8efe24
> Fix search selecting null maps, that also caused autoready issues

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
For #641 
This PR makes players send a message to others in the channel indicating they have started the game. This is needed to fix an issue like:
game host marks all players as isInGame=true, sends START message to all players, and starts the game on their side
a player leaves the lobby before they received the start message
other players receive the person leaves message before the start message. They remove the person from their side, then they receive the start message but don't start as the room is no longer full.
host quits out of game as no one connected
host returns to lobby. everyone is still marked as isInGame=true. host doesn't receive any message to tell him the players aren't in the game. This means player statuses are showing incorrectly and you can't start any more games …
> Attempt to fix game room desync by having players confirm game start

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
Fixes #683 
```
19.04. 19:42:40.783    KABOOOOOOM!!! Info:
19.04. 19:42:40.784    Type: System.NullReferenceException
19.04. 19:42:40.784    Message: Object reference not set to an instance of an object.
19.04. 19:42:41.122    Source: clientdx
19.04. 19:42:41.122    TargetSite.Name: RequestReadyStatus
19.04. 19:42:41.125    Stacktrace:    at DTAClient.DXGUI.Multiplayer.GameLobby.CnCNetGameLobby.RequestReadyStatus() in C:\Dev\xna-cncnet-client\DXMainClient\DXGUI\Multiplayer\GameLobby\CnCNetGameLobby.cs:line 736
at DTAClient.DXGUI.Multiplayer.GameLobby.MultiplayerGameLobby.ChkAutoReady_CheckedChanged(Object sender, EventArgs e) in C:\Dev\xna-cncnet-client\DXMainClient\DXGUI\Multiplayer\GameLobby\MultiplayerGameLobby.cs:line 392
```
> Fix crash when the player themself is not in the player list

- ClientCore/Extensions/StringExtensions.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/Domain/Multiplayer/CnCNet/MapSharer.cs
Fix crash when client tries to save map file with map name containing special symbols not allowed for files on NTFS.
Crash log: [ClientCrashLog_2025_05_02_23_55.txt](https://github.com/user-attachments/files/20024447/ClientCrashLog_2025_05_02_23_55.txt)
Map file to recreate crash: [14ac45ba3197c2f19a36c4269a0f263aee2ce157.zip](https://github.com/user-attachments/files/20024448/14ac45ba3197c2f19a36c4269a0f263aee2ce157.zip)
> Fix potential crash when client map name is not a valid Win32 file name

- DXMainClient/DXGUI/Generic/StatisticsWindow.cs
Currently, statistics for all games are loaded into a multi-column listbox on startup and after a game is played, causing the client to lock up if there is a large game history. The XNAListbox's AddItem is the main cause of slowness which I will address with another PR later this week.
This PR defers loading the multi-col listbox until the statistics window is actually displayed.
> Defer loading statistics listbox until StatisticsWindow is initialized and visible

- DXMainClient/DXGUI/Generic/MainMenu.cs
To prevent crash like this one:
(in this log file, please subtract line numbers of `MainMenu.cs` by 12 when viewing on the latest commit af7e44f1c67f32bd7bbb423ef3bf93464355b713)
```
12.03. 12:01:55.672    GameProcessLogic: Process started.
12.03. 12:01:56.402    Waiting for qres.dat or Syringe.exe to exit.
12.03. 12:11:17.215    GameProcessLogic: Process exited.
12.03. 12:11:21.195    KABOOOOOOM!!! Info:
12.03. 12:11:21.195    Type: System.Reflection.TargetInvocationException
12.03. 12:11:21.195    Message: Exception has been thrown by the target of an invocation.
12.03. 12:11:22.055    Source: mscorlib
12.03. 12:11:22.055    TargetSite.Name: InvokeMethod
12.03. 12:11:22.105    Stacktrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, …
```
> Fix unexpected crash from background music

- ClientCore/Statistics/StatisticsManager.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
This issue occurs when all players are marked as Ready, and the host quickly switches to a map that some players don't have before clicking Start. Players missing the map will crash.
The crash happens in `GameLobbyBase.cs` within `WriteSpawnIni` at the `if (Map.IsCoop)` check. This fix prevents the game reaching that line with a null map.
GameProcessExited is called to inform the host that the player has left the game. Without this, the host would still consider the player as IsInGame which would cause issues (I think) similar to #641.
The match statistics changes are because GameProcessExited calls them which won't work with a null map. 
If it's preferred, instead of calling GameProcessExited and making changes to match statistics, we could just call the relevant lines of …
> Fix crash when starting game with null map

- DTAConfig/OptionPanels/DisplayOptionsPanel.cs
- DTAConfig/ScreenResolution.cs
- DXMainClient/Startup.cs
```
KABOOOOOOM!!! Info:
Type: System.NullReferenceException
Message: Message: Object reference not set to an instance of an object.
Source: clientdx
TargetSite.Name: Execute
Stacktrace:    在 DTAClient.Startup.Execute()
在 DTAClient.PreStartup.Initialize(StartupParams parameters)
```
Also removes an unused function `GetBestRecommendedResolution()` that shares the same codes.
We should indeed gradually enable `#nullable` since null reference exception is the most frequent crash type of the client.
> Fix crash when the desktop resolution is too small

- ClientCore/ClientConfiguration.cs
- ClientCore/Enums/ClientTypeHelper.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- Docs/Migration-INI.md
- Docs/Migration.md
Also, minor changes are applied to the document. A placeholder of tag name `2.12.0` instead of `2.12.0.0` is used as GitVersion does not support the fourth number -- it will always be 0.
> Remove default value of ClientGameType

- ClientCore/ClientCore.csproj
- ClientCore/FileHelper.cs
- DXMainClient/Domain/Multiplayer/Map.cs
- DXMainClient/Program.cs
- Directory.Packages.props
The bug was first discovered in 2019 when I was translating Twisted Insurrection into Russian. The bug was caused by the fact that `spawnmap.ini` is always created in UTF8 encoding, even if the original file was in a different one, for example in CP1251.
Important map code in UTF8:
Important map code in CP1251:
Before patch:
After patch:
> Fix `spawnmap.ini` encoding getting messed up

- DXMainClient/Domain/Multiplayer/CnCNet/TunnelHandler.cs
Fix for a crash I received today when jumping through different rooms quickly.
> Store CurrentTunnel reference to avoid null reference

- ClientUpdater/CustomComponent.cs
- ClientUpdater/Updater.cs
Not specifying `SslProtocols` causes Windows 7 clients can not connect to TLS 1.2/1.3-only HTTPS server.
Without this PR, windows 7:
```
22.05. 01:48:42.695    Updater: Checking for updates.
22.05. 01:48:42.697    Updater: Doing version file check.
22.05. 01:48:42.698    Updater: Checking version on the server.
22.05. 01:48:42.701    Updater: Trying to connect to update mirror https://phantom.cncguild.net/updates/
22.05. 01:49:04.482    Updater: Error connecting to update mirror. Error message: An error occurred while sending the request.
22.05. 01:49:04.482    Updater: Seeking other mirrors...
22.05. 01:49:04.483    Updater: An error occured while performing version check: Unable to connect to update servers.
22.05. 01:49:04.484    Updater: File identifiers updated.
```
this error is not …
> Fix outdated TLS version support in Windows 7

- DXMainClient/DXGUI/GameClass.cs
- DXMainClient/DXGUI/Generic/LoadingScreen.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/CnCNetLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/LANGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/MultiplayerGameLobby.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/SkirmishLobby.cs
- DXMainClient/DXGUI/Multiplayer/LANLobby.cs
- DXMainClient/Online/CnCNetManager.cs
- DXMainClient/Online/Connection.cs
This PR uses dependency injection to provide a shared Random class whose seed is NOT generated from the system time but a reliable RNG from [System.Security.Cryptography.RandomNumberGenerator](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator). 
This PR solves the issues below:
- Calling `new Random()` with in a short time will get an RNG with the same seed. This makes `RandomizeChannelName()` waste some times.
- Different players might have a chance to get and register the same channel if the time is close enough in `RandomizeChannelName()`
> Avoid the abuse of random generator initialization

- ClientCore/ClientConfiguration.cs
- DXMainClient/DXGUI/Multiplayer/ChatListBox.cs
- Docs/INISystem.md
Changes:
* When a user clicks the left mouse button twice on a message containing a link in a chat, a confirmation window appears asking if they want to open the link in a browser;
* ~~When the middle mouse button is clicked, the client will instantly open the link.~~
Example:
Reference (Funky's client):
To Do:
> Improve `ChatListBox` link handling

- ClientGUI/XNAClientColorDropDown.cs
- ClientGUI/XNAColorDropDown.cs
- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
- Docs/INISystem.md
New implementation of drop-down with colors for Skirmish/LAN/Multiplayer lobby offering 3 possible types of draw items.
Closes #369, closes #760, closes #368
Code (`GameLobbyBase.ini`):
```ini
[ddPlayerColor0]
ItemsDrawMode=Icon
```
> Show colors and texts in color drop down

- ClientCore/Extensions/StringExtensions.cs
- DXMainClient/DXGUI/Generic/URLHandler.cs
- DXMainClient/DXGUI/Multiplayer/ChatListBox.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/GlobalContextMenu.cs
New implementation can handle one or more links in single message.
Example: 
Closes #762
> Handle multiple links in chat message

- DXMainClient/DXGUI/Multiplayer/CnCNet/GameCreationWindow.cs
This PR allows modders NOT defining the size of the GameCreationWindow.
This is because the height has been changed in https://github.com/CnCNet/xna-cncnet-client/pull/598 and since modders must specify the height of the GameCreationWindow before this PR (otherwise see the first screenshot titled "before" below), they will get an incorrect border if they forgot to update the height. 
Before this PR, they must manually increase the height for this window after https://github.com/CnCNet/xna-cncnet-client/pull/598. Now they can also choose to remove the size definition.
This PR will still respect for a defined size.
```diff
[GameCreationWindow]
-Size=493,204
DrawMode=Tiled
BackgroundTexture=longdescbg.png
DrawBorders=false
[GameCreationWindow_Advanced]
-Size=493,404
DrawMode=Tiled …
```
> Correct GameCreationWindow height for undefined size

- ClientCore/Enums/AllowPrivateMessagesFromEnum.cs
- DTAConfig/OptionPanels/CnCNetOptionsPanel.cs
- DXMainClient/DXGUI/Multiplayer/CnCNet/PrivateMessagingWindow.cs
This PR adds a new private message option, to filter out PM from players that are not in current channel.
Prevent adversaries from bothering players even if they got banned by a channel admin: https://github.com/CnCNet/xna-cncnet-client/pull/727#issuecomment-2902088148
Not enabled by default.
> Allow excluding private messages from players not in current channel

- DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs
For YR repo I have this:
Was wanting to create a random selector for sides, based on popular / preferred sides.
Right now I have this in GameOptions.ini:
[RandomSelectors]
Allied=0,1,2,3,4
Soviet=5,6,7,8
Ladder=0,1,2,6,6,6,9,9,9
Idea is 33% chance for allied, 33% chance for soviets, 33% chance for yuri.
If allied, you either get America, Korea or France.
If soviet, you get Iraq.
If yuri, then duh yuri is master.
I thought relisting the same side index for Iraq and Yuri under Ladder=0,1,2,6,6,6,6,9,9,9 would work, but so far the data suggests this:
America         -> 16
Korea              -> 13
France            -> 14
Iraq                  -> 12
Yuri                  -> 15
Total Games        -> 10
Computers          -> 7
Total Countries  -> 70
% As Allied      -> 61.42%
% As Soviet     -> …
> Allow randomselector to consider duplicate values

- DXMainClient/DXGUI/Generic/GameInProgressWindow.cs
This PR potentially fixes a race condition in SharedUILogic_GameProcessExited. 
Both MainMenu and GameInProgressWindow use SharedUILogic_GameProcessExited. When MainMenu's handler executes first, it disables the GameInProgressWindow. Since disabled controls don't have their Update() method called, the scheduled callback never executes.
As the WindowManager never gets disabled, this PR moves the callback to execute there instead.
Fixes #800
> Fix race condition preventing GameInProgressWindow cleanup when disabled before callback execution

- DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs
We should reset players' pings to unknown when the tunnel changes, otherwise the pings can be stale.
> Reset player pings on tunnel change
